camera_topic: "/camera/image_raw"
camera_info_topic: "/camera/camera_info"
detection_topic: "/detections"
model_path: "/home/pyy/Documents/sentiel/models/yolov8n.engine"
conf_threshold: 0.25
nms_threshold: 0.65
