terrain_analysis_node:
  ros__parameters:
    input_cloud_topic: "/livox/lidar"
    input_cloud_type: 0
    using_shenbei_mode: true
    using_robosense: false
    N_SCANS: 6
    sensorMinimumRange: 0.1
    sensorMountAngle: 0.0
    output_index: 0
    output_width: 2000
    output_height: 2000
    output_resolution: 0.05
    show_opencv: false
    show_rviz: true
    robot_height: 1.0
    robot_clearance: 0.0
    grid_size: 4.0
    break_distance: 0.1
    use_break: false
    break_distance_bias: 0.0
    use_filter: false
    filter_threshold: 0.1
    pitch_tolerance: 0
    roll_tolerance: 0
    intensity_thre: 100
    max_obs_height: 3.0
