pointlio_node:
  ros__parameters:
    use_sim_time: False
    map_file_path: "src/Point-LIO/PCD/scans.pcd" 
    common:
      lidar_type: 3 
      N_SCANS: 6
      SCAN_RATE: 10.0
      time_unit: 1e-9
      blind: 0.5
      det_range: 200.0
      fov_degree: 90.0
      point_filter_num: 1
    preprocess:
      lidar_type: 3
      scan_rate: 10.0
      blind: 0.5
      feature_extract_enable: false
      point_filter_num: 1
      dispatch_filter: 3
      max_iteration: 4
      filter_resolution: 0.2
    mapping:
      iterLimit_opt: 15
      eff_feature_frame_num: 1.56
      gyr_cov_static: 0.00001
      acc_cov_static: 0.00001
      b_gyr_cov: 0.0000001
      b_acc_cov: 0.0000001
      gyr_cov: 0.001
      acc_cov: 0.01
      gyr_cov_input: 0.0000001
      acc_cov_input: 0.0000001
      det_range: 200.0
      fov_degree: 90.0
      extrinsic_est_en: true
      extrinsic_T: [0.0, 0.0, 0.0]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]
      space_down_sample: 0.01
      surface_down_sample: 0.3
      point_filter_num: 1
      ikdtree_resolution: 0.1
      ikdtree_delete_size: 0.05
      cube_side_length: 1000
      max_iteration: 5
      moving_avg_size: 100
      maximum_points_kdtree: 200000
      planar_threshold: 0.1
    publish:
      path_publish_en: true
      scan_publish_en: true
      scan_bodyframe_pub_en: true
      dense_publish_en: true
      scan_effect_pub_en: true
      pcd_save_en: true
      extrinsic_est_en: true
    pcd_save:
      pcd_save_interval: 1
      pcd_save_dir: "/PCD/scans"
